### ISSUE TITLE
Besteffort jobs with a minimal "normal" lifetime

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar#100]
It should be great to have a certain type of jobs that are "normal" during a given time, and become besteffort after this minimal lifetime.

**Comment by augu5te** [comment]
Can you give more details about the envisioned use case ?

**Comment by bzizou** [comment]
The use case: you want to give a chance to short besteffort jobs to finish before preempting the resources. A priority job can wait a bit that the short jobs finish.

Well, saying that, I'm wondering if the solution is not simply to have a 0 priority queue in which we put those short jobs in normal mode...

cc @npf ?

**Comment by capitn** [comment]
I think you can do it with this syntax:

  oarsub -t besteffort --checkpoint=30 --signal=0 -l core=1 ./script.sh

So the besteffort job will have at least 30s to run.
--> admission rules on the "checkpoint" argument used by besteffort jobs to avoid bad user ideas ;-)

The only drawback is that the Almighty sends the signal 0 for each besteffort needed to be killed. So it could trigger a lot of SSH processes (maybe we can put a if on the signal number and if it is 0 then do nothing).
