### ISSUE TITLE
Check why OAR does not build reproducibly

### ISSUE THREAD

**Issue by npf** [oar-team/oar#102]
https://tracker.debian.org/pkg/oar

https://tests.reproducible-builds.org/rb-pkg/unstable/amd64/oar.html

**Comment by mickours** [comment]
The test says:
```
Timestamp in documentation generated by Docutils.
```
Any idea where docutils is used to generate documentation?

**Comment by mickours** [comment]
Ok It seems that OAR do build reproducibly expect when the year changes between to build!
There is no simple way to get the last commit date from the Sphinx configuration file so I fixed it  by making the copyright mention static to 2016. See ab1fb43.

@npf  can you try to rebuild the doc to see it is OK please?

**Comment by npf** [comment]
Rebuild seems ok.

Can we check that reproducibility is ok without uploading to Debian ?

**Comment by npf** [comment]
Add @vdanjean in the loop, but it should just be ok now..

**Comment by npf** [comment]
2.5.7-2 is reported ok in https://tests.reproducible-builds.org/rb-pkg/unstable/amd64/oar.html
