### ISSUE TITLE
Changes in the oarstat --gantt Json API

### ISSUE THREAD

**Issue by clement-parisot** [oar-team/oar#113]
Hello,
In the version *2.5.7-2~bpo8+1* of OAR on Debian Jessie, there is a little change in the output of the `oarstat -J --gantt` command. For example the previous command returns this type of Json:

```json
{
   "jobs" : {
      "972029" : {
         "resource_id" : [
            4886,
            4887,
            4888
         ],
         "submission_time" : 1461692371,
         "command" : "sleep 3d",
         "stop_time" : 1461893971,
         "properties" : "(((cluster='talc') AND production = 'YES') AND maintenance = 'NO') AND (max_walltime >= 201600 OR max_walltime <= 0)",
         "network_address" : [
            "talc-97.nancy.grid5000.fr",
            "talc-97.nancy.grid5000.fr",
            "talc-97.nancy.grid5000.fr"
         ],
         "state" : "Running",
         "launching_directory" : "/home/cparisot",
         "project" : "default",
         "queue_name" : "production",
         "job_name" : null,
         "job_id" : "972029",
         "types" : [
            "production",
            "production",
            "production"
         ],
         "job_type" : "PASSIVE",
         "start_time" : 1461692371,
         "user" : "cparisot",
         "walltime" : 201600
      },
[...]
```
The field **resource_id** used to be **resources** in the previous versions of OAR. Did I have to change my script and adapt them to the new syntax or is it an unintentional change ?

**Comment by npf** [comment]
Hello @clement-parisot,

I do not think resources changed for resource_id, they might be 2 different objects:
* resource_id is the identifier of a resource
* resources might be the array of resources which are allocated to a job

However, yes there was some changes to fix #82 , see 94e047a.

Unless you do report a problem with the current output, it should stay as it is, so modifying your code seems required.

Thanks

**Comment by clement-parisot** [comment]
It was just a question. I will adapt my scripts. Thank you @npf !

**Comment by lnussbaum** [comment]
From a quick glance, this is because the code used to rename some fields (so the fields in the DB didn't match the fields in the Dumper output). See https://github.com/oar-team/oar/commit/94e047a89c677a0bd777be7582996570ed45255f#diff-7cc41ee323d9c26bba8e83d42e6dd802L4238

Anyway, no big deal, but it's probably worth notifying users though. There might be other tools relying on that (other than phoenix and spy5k).

**Comment by npf** [comment]
Added to erratas for 2.5.6.
https://oar.imag.fr/oar_2.5.6
