### ISSUE TITLE
drawgantt-svg : displaying the hostname in the tooltips when possible

### ISSUE THREAD

**Issue by bpichot** [oar-team/oar#115]
When the drawgantt is made more compact by being configured with only one line per host (as it is by default in Grid'5000), it is sometimes difficult to know which line corresponds to which host, in the middle of the chart. It would be handy to display the hostnames in some tooltips, like those defined in the method "svg_states" of the class "Resource", in drawgantt-svg.php.

If I understood correctly, this is not configurable by the user.

**Comment by npf** [comment]
We could highlight the resource name on the left in the mouse_over event on the grid...

**Comment by npf** [comment]
Closed by  b34cab3af896815beee133cae7d3a19d98bab858
