### ISSUE TITLE
YAML output from API and oarnodes -Y differ

### ISSUE THREAD

**Issue by nmichon** [oar-team/oar#119]
The YAML generated by the API and the `oarnodes -Y` cli tool is different.
`oarnodes -Y` adds single quotes around some values, the API doesn't.
While values are the same, it is problematic because YAML parsers converts automatically unquoted symbols matching truthy/falsy strings (like yes, off, ...) to their boolean equivalent resulting in different values.
It seems differences exists for integer and floating point values as well.

**Comment by npf** [comment]
Hello,
can you give example, in a gist I more conveniant?

**Comment by npf** [comment]
Can you try to add @@?structure=oar@@ in your URL for the API

**Comment by npf** [comment]
can you also give the Perl/YAML packages installed on the system, e.g.
```
$ dpkg -l "*yaml*perl"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-=====================================================================================
un  libcpan-meta-yaml-perl                   <none>                    <none>                    (no description available)
ii  libyaml-libyaml-perl                     0.41-6                    amd64                     Perl interface to libyaml, a YAML implementation
ii  libyaml-perl                             1.13-1                    all                       YAML Ain't Markup Language
un  libyaml-shell-perl                       <none>                    <none>                    (no description available)
ii  libyaml-syck-perl                        1.27-2+b2                 amd64                     Perl module providing a fast, lightweight YAML loader and dumper
ii  libyaml-tiny-perl                        1.64-1                    all                       Perl module for reading and writing YAML files
```

**Comment by nmichon** [comment]
Tested with oarnodes version:
> oarnodes -V
> OAR version : 2.5.7 (Winter was not coming)

Versions of Perl/YAML packages on the same system:
```
un  libcpan-meta-yaml-perl  <none>           <none>           (no description available)
ii  libyaml-libyaml-perl    0.41-6           amd64            Perl interface to libyaml, a YAML implementation
ii  libyaml-perl            1.13-1           all              YAML Ain't Markup Language
un  libyaml-shell-perl      <none>           <none>           (no description available)
ii  libyaml-syck-perl       1.27-2+b2        amd64            Perl module providing a fast, lightweight YAML loade
```

Here is an example output for a single resource:
https://gist.github.com/nmichon/c915463f8dfa130e0385670d8d43de02

I tried adding the `?structure=oar` parameter but the output is odd and not comparable: 
```
---
1: 47708104
```

**Comment by bzizou** [comment]
I couldn't find why "oarnodes -Y" adds some quotes and not the API...
Is it possible for you to use JSON outputs instead of YAML?
```oarnodes -r 1 -J``` and ```/resources/1.json```
Json is most likely to be maintained in the future, and Yaml will be deprecated...

**Comment by npf** [comment]
close/wont-fix: oarstat -Y is different from the API output as well, at the structure level. There's no plan to make oarnodes/oarstat give the exact same output as the API in OAR2.
