### ISSUE TITLE
Drain resources vs job expected resources

### ISSUE THREAD

**Issue by npf** [oar-team/oar#12]
When submitting a new job for 1 host while 1 core is in the draining state, it can happen that one gets the host which the draining core belongs to.

One could expect that this host wouldn't be selected since 1 of its cores is not available.

Should something be changed in order to have that behavior ?

**Comment by capitn** [comment]
If you know that the wanted host has 4 cores (for example) then add:

  oarsub -l host=1/core=4 ...

Indeed the '-p drain='NO'" is a filter so the resources with drain='NO' are not seen by the scheduler when you say host=1.

I think it is possible to change this behaviour by moving the '-p' and {...} oarsub filter outside of the SQL queries that retrives the eligible resources. But it is a big change.
