### ISSUE TITLE
Check  if my installation is well done : message = No enough matching resources (no_matching_slot)

### ISSUE THREAD

**Issue by iamadou** [oar-team/oar#125]
Hello,

I tried to check if my installation is well done by typing this command as classical user: 
   oarsub -t deploy -l /nodes=1 "/bin/sleep 5" 
The response from the server is is this form:
   [ADMISSION RULE] Set default walltime to 7200.
   [ADMISSION RULE] Modify resource description with type constraints
   OAR_JOB_ID=9
Then, my expectation is that my job 9 is under running
By typing oarsub -f -j 9, the reponse is:
Job_Id: 9
    job_array_id = 9
    job_array_index = 1
    name = 
    project = default
    owner = chuck
    state = Waiting
    wanted_resources = -l "{type = 'default'}/network_address=1,walltime=2:0:0" 
    types = deploy
    dependencies = 
    assigned_resources = 
    assigned_hostnames = 
    queue = default
    command = /bin/sleep 5
    launchingDirectory = /root
    stdout_file = OAR.9.stdout
    stderr_file = OAR.9.stderr
    jobType = PASSIVE
    properties = ((deploy = 'YES') AND desktop_computing = 'NO') AND drain='NO'
    reservation = None
    walltime = 
    submissionTime = 2017-02-07 14:21:45
    cpuset_name = chuck_9
    initial_request = oarsub -t deploy -l /nodes=1 /bin/sleep 5
    **message = No enough matching resources (no_matching_slot)**
    scheduledStart = no prediction
    resubmit_job_id = 0
    events = 
Even after one day, my job remains in waiting state and the output message is: No enough matching resources. I don't if someone have already encountered this issue after their install or if you know what is the mistake, it will be helpful for me. 
Thank

**Comment by npf** [comment]
Did you actually set the deploy property to YES to some resources ? (with oarnodesetting)
