### ISSUE TITLE
Deadlock in DB while Finishing

### ISSUE THREAD

**Issue by maedoc** [oar-team/oar#136]
I've got OAR 2.5 on Debian w/ Postgres, and I'm seeing stuff like
```
2017-05-05 14:47:06 CEST ERROR:  current transaction is aborted, commands ignored until end of transaction block
2017-05-05 14:47:06 CEST STATEMENT:     SELECT *
	                                FROM jobs
	                                WHERE
	                                    job_id = 6023695
	                            
2017-05-05 14:47:06 CEST ERROR:  current transaction is aborted, commands ignored until end of transaction block
2017-05-05 14:47:06 CEST STATEMENT:    UPDATE jobs
	                    SET
	                        state = 'Terminated'
	                    WHERE
	                        job_id = 6023695 AND
	                        state != 'Error' AND
	                        state != 'Terminated' AND
	                        state != 'Terminated'
```
and
```
2017-05-05 14:47:13 CEST ERROR:  deadlock detected
2017-05-05 14:47:13 CEST DETAIL:  Process 21752 waits for ShareLock on transaction 42971645; blocked by process 21682.
	Process 21682 waits for ShareLock on transaction 42971665; blocked by process 21752.
	Process 21752:  UPDATE resources
	                            SET next_state = 'Alive', next_finaud_decision = 'NO'
	                            WHERE
	                                network_address = 'n23'
	                          
	Process 21682: UPDATE resources
	                SET
	                    last_job_date = 1493988426
	                FROM assigned_resources
	                WHERE
	                    assigned_resources.moldable_job_id = 6036140 AND
	                    assigned_resources.resource_id = resources.resource_id
	               
2017-05-05 14:47:13 CEST HINT:  See server log for query details.
2017-05-05 14:47:13 CEST STATEMENT:   UPDATE resources
	                            SET next_state = 'Alive', next_finaud_decision = 'NO'
	                            WHERE
	                                network_address = 'n23'
```

I had to  `UPDATE jobs SET state='Terminated' WHERE state='Finishing';` and `service oar-server restart` to get going again.

_aside_ I'm also seeing just about every `oar*` command results in
```
2017-05-05 14:47:17 CEST LOG:  could not receive data from client: Connection reset by peer
2017-05-05 14:47:17 CEST LOG:  unexpected EOF on client connection
```
I'm not sure if this is expected or bad network config on my side.

*anyway my question is the following:* this seems to happen more and more, and my guess is that the deadlock doesn't show up when you've got a few thousand jobs, but our jobs table here has 6.2e6 jobs, which makes those timeouts and deadlocks more likely. Are there any config options we can tune to avoid this?

**Comment by maedoc** [comment]
I saw the snippt
```
export OARCONFFILE=/etc/oar/oar.conf
perl -e 'use OAR::IO; $db = OAR::IO::connect(); OAR::IO::set_job_state($db,42,"Error")'
```
and looked up the source for `set_job_state` and I see it's doing a bit more that just updating the job state, so I rolled back the database and running this on each job.

It's fairly slow ~5s per call (in a loop in a perl script over Finishing jobs), again is the normal? should we reset the database?

**Comment by npf** [comment]
Hello @maedoc,
What version of OAR do you use exactly ? 2.5.4 ? 2.5.7 ?

Regarding jobs staying in the Finishing state, this happens when the OAR service is not shutdown nicely -> corruption in a job's state automata. With recent versions, the oardel command provides an option to fix the issue: no need to run the snippet.

Regarding the 6M jobs in your setup, I don't think this should be an issue. Other similar installations did not report problems. But yes, if acceptable to you, resetting your database will for sure help to make your problems vanish...

**Comment by maedoc** [comment]
```bash
root@frontal:~# oarsub -V
OAR version : 2.5.2 (tzuhtzjo:m uy-u:xlaju:n pik)
```
I guess bumping up to a more recent version would be a good thing to do while purging the database. I'm assuming there are no DB migrations.

Is there any docs about tables would be safe to purge? I haven't studied the DB schema enough to know and didn't see anything on topic in the docs.

**Comment by npf** [comment]
There will be a database migration to run (oar-database command) with newer versions, unless you restart with a fresh database setup (need to recreate resources et admission rules).

What version a Debian do you use ? 2.5.2 is indeed pretty old. Please use Debian backport to get the last version of OAR possibly.

**Comment by maedoc** [comment]
Wheezy, according to `/etc/apt/sources.list`.. thanks for the help. I'll close this issue in the hopes the bug responsible is already fixed in a newer version
