### ISSUE TITLE
Strange SQL where clause in IO::set_node_state

### ISSUE THREAD

**Issue by augu5te** [oar-team/oar#140]
A look at set_node_state function exhibits a exhibits a nonsense where clause.

`sub set_node_state($$$$) {
    my $dbh = shift;
    my $hostname = shift;
    my $state = shift;
    my $finaud = shift;

    if ($state eq "Suspected"){
        if ($dbh->do("  UPDATE resources
                    SET state = \'$state\', finaud_decision = \'$finaud\', state_num = $State_to_num{$state}
                    WHERE
                        network_address = \'$hostname\'
                        AND (state = \'Alive\'
                             OR (state = \'Suspected\' AND \'$finaud\' = \'NO\' AND finaud_decision = \'YES\'))
                ") <= 0){`

The strange part is `\'$finaud\' = \'NO\' `    $finaud  should by a column name but  it  is set in modules/node_change_state.pl to NO or YES .

**Comment by npf** [comment]
Well, it's just ugly :-)
If $finaud is not 'NO' then we should just not do any request...

**Comment by capitn** [comment]
this is just to avoid to update the resource table in case of state=Suspected and $finaud=YES.
$finaud is not a column name but a value.
This avoids to add more Perl code to check if the update statement must be performed or not in the case of state=Suspected.

I'm not sure it's ugly :-)

**Comment by npf** [comment]
closing
