### ISSUE TITLE
Allow oarnodesetting -s Suspected

### ISSUE THREAD

**Issue by npf** [oar-team/oar#141]
Maybe with a --force.

External program could be interested in placing nodes in the suspected state, e.g. on Grid'5000 after a deploy job, nodes are set to Absent and stay Absent if the kareboot failed. It is wanted to be allowed to mark them as suspected.

**Comment by npf** [comment]
@lnussbaum: for the current purpose, it could also be achieved with setting the comment field or a dedicated field: to "rebooting"  then if kareboot is ok -> "booted". If not "reboot failed".

That way, if a node is:
- absent/"rebooting" -> we are still in the kareboot wrapper, wait and see.
- absent/"reboot failed" (set by the wrapper after a failed kareboot or timeout) ->  phoenix can trap it.
- absent/"boot ok" (set by the wrapper after a sucessful kareboot, but somehow the boot process failed to run the oar service / g5k check) -> phenix can trap it

...

**Comment by npf** [comment]
@capitn, apart from that case, do you see any problem with allowing Allow oarnodesetting -s Suspected

**Comment by capitn** [comment]
Just the concept of the Suspected state meanings.
Suspected is just to say to the admin/users that the node was **auto**-detected as unhealthy (notably by the PINGCHECKER command).

**Comment by npf** [comment]
@lnussbaum : please notice that the suspected state is possibly associated to a cause (be it finaud or not). 

Hence forcing a change to that state for debugging is not so meaningful, since it won't come from a real cause. 

So, since there are 2 motivation for this issue:
1. add a resource state in OAR to manage the kadeploy use case
2. enable setting a resource state to Suspected for debugging purposes
I suggest to consider the 2 separately. 

Said differently:
* 2. does not motivate (relate to)  1. 
* 1. is better to be handled as suggested in my 2nd comment.

**Comment by lnussbaum** [comment]
erm, still, the original issue of being able to set a resource to Suspected remains. Typically, for debugging phoenix, that would be really helpful
