### ISSUE TITLE
Error creating MySQL database: column 'ssh_private_key' can't have a default value

### ISSUE THREAD

**Issue by ApolloBian** [oar-team/oar#149]
I was using `oar-database --create --db-admin-user $admin --db-admin-pass $pass` to create database when I ran into this following error message:
```bash
ERROR 1101 (42000) at line 90: BLOB, TEXT, GEOMETRY or JSON column 'ssh_private_key' can't have a default value
Fail to execute /usr/lib/oar/database/mysql_structure.sql.
```
and fail to create the database.

**Comment by ApolloBian** [comment]
Mysql version 5.7.21

**Comment by ApolloBian** [comment]
I was able to create mysql database and get resources added to it with this modification, and didn't run into any further errors, as I recall.

**Comment by npf** [comment]
Is your cluster running ? For the tests I've done using oar-vagrant and forcing the installation of mysql 5.7, many things break.
→ for now we won't support Mysql 5.7 I fear. MariaDB is ok, but in any case, PostgreSQL is the prefered database engine for OAR.

**Comment by npf** [comment]
wontfix, closing.
