### ISSUE TITLE
Postgresql deadlocks with oarapi.pl since last update (2.5.4)

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar#16]
Since the last update, postgresql frequently deadlocks on TRUNCATE queries.
Here is an abstract of my oar.log file:

DBD::Pg::db do failed: ERROR:  deadlock detected
DETAIL:  Process 27321 waits for AccessExclusiveLock on relation 61813 of database 61666; blocked by process 27446.
Process 27446 waits for AccessShareLock on relation 61791 of database 61666; blocked by process 27321.
HINT:  See server log for query details. at /usr/share/perl5/OAR/IO.pm line 6374.
DBD::Pg::db do failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block at /usr/share/perl5/OAR/IO.pm line 6380.
DBD::Pg::db do failed: ERROR:  current transaction is aborted, commands ignored until end of transaction block at /usr/share/perl5/OAR/IO.pm line 6385.

I replaced the TRUNCATE postgresql command with a DELETE one at the given line of the OAR/IO.pm file, and the problem seems to have disappeard.

A google search on "truncate postgresql deadlock" gives a lot of results...

**Comment by capitn** [comment]
I commited the DELETE instead of TRUNCATE statements.
