### ISSUE TITLE
oarnodes is very slow

### ISSUE THREAD

**Issue by npf** [oar-team/oar#160]
SQL requests are not factorized, which cause oarnodes to be very slow on big platforms.

For ref: https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=9600

**Comment by snoir** [comment]
Fixed by multiples commits which factorize SQL queries made by oarnodes: a63cf2cadfb443289cadbb8a3954c8fc2c6dcfda, ae4b19fe6b125f7508a4b7d3994b0645e41f5ef3, f0e12693e22a7bc7d6767316ec09c0438e0d18bf, 74cadd7c0e0977d343957010372e9dd9c6c386e3
