### ISSUE TITLE
oar-server crashes on Almighty line 521

### ISSUE THREAD

**Issue by matthieu637** [oar-team/oar#162]
Hello,
Sometime the oar-server crashes with those logs : 

```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/^^V^C^@^@S^A^@^@O^C^@?G×÷º,îê²`~ó^@ý<82>{ <-- HERE ¹Õ<96>Èw<9b>æÄÛ<=Ûoï^Pn$/ at /usr/lib/oar/Almighty line 521.
find: '/tmp/./.mount_cryptoZMZ88S': Permission denied
```

I'm using Ubuntu 18.04.1 LTS, oar-server 2.5.8~rc8, perl v5.26.1 and postgresql 10+190.

**Comment by matthieu637** [comment]
There was only those 2 lines. 

With LOG_LEVEL=3, here is the 1 min logs preceding a crash (with cat -e) : [logs](https://justpaste.it/6r4i3)  (at the end there is also the "Unescaped left brace...").
It rarely happen (once / 2 weeks).

The server is running on a VM (no crypto mount) within one of the node of the cluster.

**Comment by npf** [comment]
There is apprently something weired in your setup that sends:
```
[debug] [2019-01-14 20:50:10.048] [Almighty] Appendice has read on the socket : ^@^@^@[^@^C^@^@user^@test^@database^@test^@client_encoding^@UNICODE^@DateStyle^@ISO^@TimeZone^@US/Pacific$

[debug] [2019-01-14 20:50:10.048] [Almighty] Got command ^@^@^@[^@^C^@^@user^@test^@database^@test^@client_encoding^@UNICODE^@DateStyle^@ISO^@TimeZone^@US/Pacific, 99 remaining$

[debug] [2019-01-14 20:50:10.049] [Almighty] Got command Time, 98 remaining$

[debug] [2019-01-14 20:50:10.049] [Almighty] Command queue : ^@^@^@[^@^C^@^@user^@test^@database^@test^@client_encoding^@UNICODE^@DateStyle^@ISO^@TimeZone^@US/Pacific Time$

[debug] [2019-01-14 20:50:10.049] [Almighty] Qtype = [^@^@^@[^@^C^@^@user^@test^@database^@test^@client_encoding^@UNICODE^@DateStyle^@ISO^@TimeZone^@US/Pacific]$

[debug] [2019-01-14 20:50:10.049] [Almighty] Unknown command found in queue : ^@^@^@[^@^C^@^@user^@test^@database^@test^@client_encoding^@UNICODE^@DateStyle^@ISO^@TimeZone^@US/Pacific$
```
to the socket Almighty (oar-server orchestrator) listen on (tcp *:6666, see `sudo netstat -tlpn`).

I guess an interference from something outside of OAR, trying to communicate on to 6666 tcp port ?

**Comment by matthieu637** [comment]
Indeed I redirected every entries from HOST:6666 to VM:6666 so that every nodes can speak to the server. 
Is it unnecessary ? should only the frontend be able to contact the server on port 6666?

**Comment by npf** [comment]
Yes. If I understand, you have a complex setup, with network redirection in the middle instead of a flat LAN. Should you use VMs, why not using a "bridge" mode... Closing. Please report your installation issues to the oar-users@ mailing list, not to the OAR dev github issues.
