### ISSUE TITLE
SQL performance issue - accounting for the fairsharing scheduler

### ISSUE THREAD

**Issue by npf** [oar-team/oar#167]
From @lnussbaum :

la requete pour récupérer les jobs à analyser, lancée toutes les heures, fait
partie des requetes les plus coûteuses.

j'ai tenté de la réécrire en:
```
explain (ANALYZE, COSTS, VERBOSE, BUFFERS)
SELECT jobs.start_time, 
       jobs.stop_time, 
       moldable_job_descriptions.moldable_walltime, 
       jobs.job_id, 
       jobs.job_user, 
       jobs.queue_name, 
       Count (assigned_resources.resource_id), 
       jobs.project 
FROM   jobs
INNER JOIN moldable_job_descriptions ON jobs.assigned_moldable_job =
moldable_job_descriptions.moldable_id
INNER JOIN assigned_resources ON assigned_resources.moldable_job_id =
moldable_job_descriptions.moldable_id
INNER JOIN resources ON assigned_resources.resource_id = resources.resource_id
WHERE  jobs.accounted = 'NO' 
       AND ( jobs.state = 'Terminated' 
              OR jobs.state = 'Error' ) 
       AND jobs.stop_time >= jobs.start_time 
       AND jobs.start_time > 1 
       AND resources.type = 'default' 
GROUP  BY jobs.start_time, 
          jobs.stop_time, 
          moldable_job_descriptions.moldable_walltime, 
          jobs.job_id, 
          jobs.project, 
          jobs.job_user, 
          jobs.queue_name; 
```
(ce qui est équivalent) mais ça ne marche pas mieux. Le problème est que
postgres décide de faire un seq scan sur moldable_job_descriptions, alors qu'en
théorie les index sont là pour l'éviter.

l'index que j'ai essayé d'ajouter est:
CREATE INDEX ix_jobs_to_account ON jobs(job_id, assigned_moldable_job)
WHEREaccounted = 'NO' AND ( state = 'Terminated' OR state = 'Error' ) AND
stop_time >= start_time AND start_time > 1;
(mais il n'est pas utilisé)

**Comment by augu5te** [comment]
Do you have information/log about its cost and its impact ? 
As a temporary solution, I suggest to split the request in two or three:
1) Job w/ assigned_moldable_job 
2) moldable_walltime
3) Count of assigned_resources.

**Comment by lnussbaum** [comment]
I don't have precise information. It was one of the top 2-3 queries in terms of cumulated CPU time used on G5K. The target should be to avoid the seq_scan, not to get the same execution time spread over 3 queries :)

**Comment by snoir** [comment]
Is fixed by a change of behavior in the accounting process, commit e67d3fa80baa78116d5d5f84a3db4943fdcb6a8a
