### ISSUE TITLE
Memory usage too high in Perl schedulers

### ISSUE THREAD

**Issue by capitn** [oar-team/oar#17]
On a clusteer with 5000 resources and 200 waiting jobs the memory usage of the scheduler can reach up to 1GiB. This is very high!!!

When I check the Perl documentation
  http://learn.perl.org/faq/perlfaq3.html#How-can-I-free-an-array-or-hash-so-my-program-shrinks
it seems that there is no garbage collector that will free the gantt tree structures automatically (I think the memory used comes from this because we do a lot of dclone on them).

2 solutions:
  - find a way to force Perl to free unused data strucures
  - create a new process (fork) for the scheduler part that produces a lot of data structure

Does someone has a good idea???

**Comment by npf** [comment]
What part of the code/data is so greedy on memory  ? Regarding the gantt structure, I fear we cannot unallocate much. What about temporary data in the resource lookup functions ? Could we use some unset of delete statement as proposed in the faq ?

**Comment by capitn** [comment]
I think it come from the resource tree stuctures that we clone a lot (for each gantt hole).
I'll try to implement a "destroy" function for this module and see if it is better.

Note: this beaviour was always there but when we use the multi-process scheduler implementation a lot of memory is freed when the fork terminates.
