### ISSUE TITLE
Rest API issue when submitting job with specific directory

### ISSUE THREAD

**Issue by snoir** [oar-team/oar#180]
In the POST request, if `directory` is set to something other than the user's home directory, the job cannot start.

The job will try to start from the supplied `directory`, however, the `oarapi.subscript.XXXX` file containing the job command is written into the user's home directory. As OAR tries to launch the `oarapi.subscript.XXXX` file inside the specified `directory`, it fails.

The workaround is to add in the POST request the `workdir` field, containing the same string as the `directory` field.

It is a bit odd to use both, and might be better to only use `directory` (making OAR rest API to write the subscript file in the correct directory).

**Comment by npf** [comment]
I do not reproduce. May it be a G5K job api bug only ?
