### ISSUE TITLE
OAR does not export environment variables to all nodes in the reservation

### ISSUE THREAD

**Issue by mahendrapaipuri** [oar-team/oar#189]
Hello,

I have been using [grid5000](https://www.grid5000.fr/w/Grid5000:Home) for my work to test hybrid MPI+OpenMP codes. The clusters of grid5000 uses OAR for job reservation and scheduling. I have noticed that, in both interactive and non-interactive modes, OAR applies the environment variables defined by the user only on the head node (first node in the reservation). 

This can be an issue with the env variables like `OMP_NUM_THREADS` in hybrid codes. I have been using a workaround by exporting these variables using OpenMPI `-x` flag to all the nodes in the reservation. Ideally, this should be handled by the scheduler by exporting all the env variables within the job context to all the nodes in the reservation. This is the default behaviour of SLURM, PBS and LSF.

**Comment by npf** [comment]
Hello, if I understand well, you would like processes run by mpirun from the head node to other every nodes to have some environment variables available on other nodes just like on the head node. If correct this seems a job connector question, i.e. oarsh/ssh question.

Did you try on Grid'5000 to use the `allow_classic_ssh` job type and then ssh as the mpi connector and see if it works better than with oarsh ? SSH may require some `SendEnv` directives which could spread the environment variable definition.

Not sure about other tools, but if SSH is used as the connector from head node to other node, it seems not so OAR specific ?

**Comment by mahendrapaipuri** [comment]
Hello @npf, thanks for the response. Yes, you understood it well and I believe that should be default behaviour. I am concerned with the env variables like `PATH`, `LD_LIBRARY_PATH`, `OMP_NUM_THREADS`, _etc_. So, I have tested with a simple script that prints env variable that is defined in OAR job script:
```
#!/bin/bash
echo "Host `hostname` has $OMP_NUM_THREADS setting"
```
And I launched with following commands in the job scrips:
```
#!/bin/bash -l

#OAR -n env-test
#OAR -l host=2,walltime=00:15:00
#OAR -p cluster='dahu'
#OAR -t allow_classic_ssh # used it only for ssh connector
#OAR -O oar-job.out
#OAR -E oar-job.out

echo "Running on master node: `hostname`"
export OMP_NUM_THREADS=8

mpirun --map-by node --mca orte_rsh_agent "oarsh" --machinefile $OAR_NODEFILE -np 2 ./print_env.sh
mpirun --map-by node --mca orte_rsh_agent "ssh" --machinefile $OAR_NODEFILE -np 2 ./print_env.sh # I set -t allow_classic_ssh flag for this config
```
And the output I got in both cases is:
```
Running on master node: grisou-33.nancy.grid5000.fr

Host grisou-5.nancy.grid5000.fr has  setting
Host grisou-33.nancy.grid5000.fr has 8 setting
```
Well, regarding the job connectors, I thought OAR manages them and they come shipped with OAR. That is why I put up the issue here. If that is not the case, I am sorry for the noise and probably take up this issue to grid5000 team.

**Comment by npf** [comment]
Hello @mahendrapaipuri 
`oarsh` is a wrapper on top of the `ssh` client that uses a separate instance of the `sshd` service. But we try to do no more than the original `ssh`/`sshd` do. 

So please first try to see what would be sufficient for your use case with using `ssh`/`sshd` (thus with the `-t allow_classic_ssh` job type on Grid'5000). From my viewpoint, requesting to add `AcceptEnv` directives to the sshd configuration for any software that would like `ssh` to let send environment variables from host to host does not seem right. Of course, `openmpi` is not any software, but ...

**Comment by mahendrapaipuri** [comment]
Hello @npf, Infact I could solve the issue simply by passing `--mca mca_base_env_list` flag with list of `env` variables that I want to pass to others nodes in reservation. OpenMPI can take care of it quite nicely. 

I raised this issue, as there is no info about this behaviour from OAR in the documentation (I use grid'5000 documentation as my reference for OAR). For instance, if someone is trying to run hybrid MPI+OpenMP code and if they set `OMP_NUM_THREADS` variable, obviously this setting will be respected only on the head node and rest of nodes will use all (physical+logical) cores for OpenMP blocks. That can give a misleading insight on performance of the underlying code. I think there is need to update the MPI section in the grid'5000 documentation to clearly mention this behaviour. 

I understand the risk associated with adding `AcceptEnv` directive to `sshd` configuration. I am not expert in developing schedulers, but, perhaps it is worth looking on how OpenPBS/PBS Torque implements this? From my understanding, PBS and OAR has very similar architectures (at least the way they spawn the MPI tasks or may be I am completely wrong?).

**Comment by npf** [comment]
Thanks. This is now documented:
* https://oar.imag.fr/wiki:passing_environment_variables_to_openmpi_nodes
* https://www.grid5000.fr/w/Run_MPI_On_Grid%275000#Passing_environment_variables_to_nodes
