### ISSUE TITLE
Support of cgroupsv2 by OAR ?

### ISSUE THREAD

**Issue by mneveu-mx** [oar-team/oar#201]
Hello,

The support of cgroupsv2 is on the roadmap of OAR ? It is currently available ?
In the perl code, the memory controller can be set by OAR with the parameter "memory.limit_in_bytes". In cgroupsv2, the new syntax is memory.max or memory.high. So i suppose OAR don't support today cgroupsv2.

Thanks,
Maxime

**Comment by npf** [comment]
Yes. OAR 2 does not use cgroup v2 for now.
