### ISSUE TITLE
Make the content of OAR_FILE_NODE easily available through the API

### ISSUE THREAD

**Issue by bzizou** [oar-team/oar#21]
(Initially posted on gforge by David Margery)

Using OAR's API, it is possible to use the undocumented relation /jobs/<id>/nodes to get the list of nodes of a job.
On the other hand, OAR_FILE_NODE gives the list of node of a job, with one entry by core (is that a config parameter ?)

It would be usefull to have /jobs/<id>/nodes_with_repeats or at least /jobs/<id>/nodes with a weight given to each node to easily get as much information as OAR_FILE_NODE

**Comment by capitn** [comment]
In /etc/oar/oar.conf, there are:

    NODE_FILE_DB_FIELD="network_address"
    NODE_FILE_DB_FIELD_DISTINCT_VALUES="resource_id"

to specify the DB field to use for the value inserted in $OAR_NODE_FILE. So the field "network_address" will be printed for each different "resource_id".

The Perl code can be seen in sources/core/tools/job_resource_manager_cgroups.pl, line 269.

**Comment by npf** [comment]
@bzizou: for 2.6 ?
