### ISSUE TITLE
Dead code in oarsh ?

### ISSUE THREAD

**Issue by npf** [oar-team/oar#30]
@capitn, do you agree that this code is dead in oarsh ?

 # -2- try connection using a job key pushed by OAR for a job using the job key mechanism. 
 # (oarsh is run from one of the node of the job) 
 TMP_JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/$OARDO_USER.jobkey"
 if [ -r $TMP_JOB_KEY_FILE ]; then
    umask $OLDUMASK
    exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -i $TMP_JOB_KEY_FILE  "$@"
    echo "oarsh: Failed to connect using the cpuset job key: $TMP_JOB_KEY_FILE"
    exit 4
 fi

**Comment by capitn** [comment]
OARDO_USER is the user name not "oar" because oarsh is called by the oarsh_oardo (oardo.c) wrapper that set the OARDO_USER.

But I'm agree, I don't understand which functionality is implemented by this piece of code...
I think the comment is ok for the next part of the code not this one.

We don't have a mechanism of "key by user" this is no sense because you can have several jobs on a same node.

**Comment by npf** [comment]
Also in the next bloc below, I think "export OAR_CPUSET" and "export OAR_JOB_USER=$OARDO_USER" are useless since they are set as part of the public key line in the authorized_keys file on the remote:

 if [ "$CPUSET_PATH" != "" ]; then
    if [ -r /proc/self/cpuset ]; then
        OAR_CPUSET=$(< /proc/self/cpuset)
        if [ "${OAR_CPUSET%/*}" = "$CPUSET_PATH" ] || [ "${OAR_CPUSET%/*}" = "$CPUSET_PATH/" ]; then
            JOB_KEY_FILE="$OAR_RUNTIME_DIRECTORY/${OAR_CPUSET##*/}.jobkey"
            if [ -r $JOB_KEY_FILE ]; then
                umask $OLDUMASK
                exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -i $JOB_KEY_FILE "$@"
                echo "oarsh: Failed to connect using the cpuset job key: $JOB_KEY_FILE"
                exit 4
            fi
            export OAR_CPUSET
            export OAR_JOB_USER=$OARDO_USER
            umask $OLDUMASK
            exec $OPENSSH_CMD $OARSH_OPENSSH_DEFAULT_OPTIONS -oSendEnv="OAR_CPUSET OAR_JOB_USER" "$@"
            echo "oarsh: Failed to connect using cpuset environement"
            exit 5
        fi
    fi
 fi

**Comment by npf** [comment]
It's actually for the cases where job keys are in use. Nevermind.
