### ISSUE TITLE
SQL query for getting information on every jobs in a job_id interval

### ISSUE THREAD

**Issue by jgaidamour** [oar-team/oar#38]
Statsg5k (a usage reporting tool for OAR clusters) makes SQL queries directly on OAR databases for getting information on jobs. At each update of statsg5k, the tool queries the OAR database for getting jobs that have been created since the last update of statsg5k. The SQL query aims at getting every new jobs, even unfinished one. If a job is not yet finished, statsg5k keeps it on a "watchlist" for later processing.

The SQL query used for getting all the jobs in a [job_id_min, job_id_max] range is:

```sql
(
   SELECT jobs.job_id, jobs.start_time, jobs.stop_time, jobs.job_user, jobs.queue_name, jobs.job_type, jobs.state, resources.cluster, resources.type as resource_type, count(resources.resource_id) as nb_cores
   FROM resources
   INNER JOIN jobs
     ON jobs.job_id >= job_id_min
     AND jobs.job_id <= job_id_max
   INNER JOIN assigned_resources
     ON assigned_resources.resource_id = resources.resource_id
   INNER JOIN moldable_job_descriptions
     ON assigned_resources.moldable_job_id = moldable_job_descriptions.moldable_id
     AND jobs.job_id = moldable_job_descriptions.moldable_job_id
   GROUP BY jobs.job_id, resources.cluster
  )
 UNION
  (
   SELECT  jobs.job_id,  jobs.start_time,  jobs.stop_time,  jobs.job_user,  jobs.queue_name,  jobs.job_type,  jobs.state,  resources.cluster,  resources.type as resource_type, count(resources.resource_id) as nb_cores
   FROM resources
   INNER JOIN jobs
     ON jobs.job_id >= job_id_min
     AND jobs.job_id <= job_id_max
   INNER JOIN gantt_jobs_resources
     ON gantt_jobs_resources.resource_id = resources.resource_id
   INNER JOIN moldable_job_descriptions
     ON gantt_jobs_resources.moldable_job_id = moldable_job_descriptions.moldable_id
     AND jobs.job_id = moldable_job_descriptions.moldable_job_id
   GROUP BY jobs.job_id, resources.cluster
 )
```

It seems that this query does not capture all the jobs as we found out that some jobs are missing on the statsg5k database. Any idea on how to achieve what we want ?

We welcome any suggestions or insight but to fix the problem, we were thinking on doing two distinct queries:
- one query for getting the finished jobs:
```sql
SELECT jobs.job_id, jobs.start_time, jobs.stop_time, jobs.job_user, jobs.queue_name, jobs.job_type, jobs.state, resources.cluster, resources.type as resource_type, count(resources.resource_id) as nb_cores
   FROM resources
   INNER JOIN jobs
     ON jobs.job_id >= job_id_min
     AND jobs.job_id <= job_id_max
   INNER JOIN assigned_resources
     ON assigned_resources.resource_id = resources.resource_id
   INNER JOIN moldable_job_descriptions
     ON assigned_resources.moldable_job_id = moldable_job_descriptions.moldable_id
     AND jobs.job_id = moldable_job_descriptions.moldable_job_id
   GROUP BY jobs.job_id, resources.cluster
```

- one query for getting all the job_id in the range:
```sql
SELECT jobs.job_id FROM jobs WHERE jobs.job_id >= job_id_min AND jobs.job_id <= job_id_max
```

In this way, jobs that are not captured by the first query should go on the watchlist.

**Comment by capitn** [comment]
If a job is never launched then there is no corresponding "assigned_resources.moldable_job_id". In this case the query is not working.
For example, a job can be deleted (oardel) before it was launched.

Is there other kind of jobs that are not handled by your query?

Another thing is that you can use "jobs.assigned_moldable_job" for jobs that were launched instead of doing a JOIN on the moldable_job_descriptions table. If the job was not yet launched then the value is jobs.assigned_moldable_job=0.

**Comment by jgaidamour** [comment]
> For example, a job can be deleted (oardel) before it was launched.

If a job is deleted before it was launched, I don't care about it (in the context of statg5k). So it is OK if such jobs are not handled by the query.

> Is there other kind of jobs that are not handled by your query?

Yes. On my initial SQL query, some jobs with non-zero running time are not handled. After talking with *npf*, I suspect that the problem is the use of `gantt_jobs_resources`  =on the second part of the query (vs. using the `gantt_jobs_resources_visu` table I was unaware of). If I run the same query several days later, I get jobs that was initially missing (most probably because the state of this jobs changed between the two queries).

**Comment by jgaidamour** [comment]
> Another thing is that you can use "jobs.assigned_moldable_job" for jobs that were launched instead of doing a JOIN on the moldable_job_descriptions table. If the job was not yet launched then the value is jobs.assigned_moldable_job=0.

Does this look right to you ?
```sql
SELECT jobs.job_id,
       jobs.start_time,
       jobs.stop_time,
       jobs.job_user,
       jobs.queue_name,
       jobs.job_type,
       jobs.state,
       resources.cluster,
       resources.type as resource_type,
       count(resources.resource_id) as nb_cores
FROM  jobs
INNER JOIN assigned_resources
  ON  jobs.assigned_moldable_job = assigned_resources.moldable_job_id
INNER JOIN resources
  ON  resources.resource_id = assigned_resources.resource_id
WHERE jobs.job_id >= job_id_min
  AND jobs.job_id <= job_id_max
  AND stop_time !=0 AND stop_time!=start_time 
GROUP BY jobs.job_id, resources.cluster
```

**Comment by npf** [comment]
Dumb question: is it on purpose that you use INNER JOIN, but not another join  e.g. LEFT JOIN as use in the drawgantt code ?

For ref: http://stackoverflow.com/questions/5706437/whats-the-difference-between-inner-join-left-join-right-join-and-full-join

**Comment by jgaidamour** [comment]
> is it on purpose that you use INNER JOIN

No particular reason. It is just because I started from existing code. I think you are right. With a LEFT JOIN, I can get all the jobs, even those without assigned resources.

**Comment by npf** [comment]
Closing.
