### ISSUE TITLE
IO::get_job_current_hostnames vs IO::get_cpuset_values_for_a_moldable_job

### ISSUE THREAD

**Issue by npf** [oar-team/oar#39]
@capitn: 
I'm looking at get_job_current_hostnames and get_cpuset_values_for_a_moldable_job functions of IO.pm:
I'm wondering why the 1st one needs to look at the moldable_job_descriptions table, while the 2nd does not ?

Also, bipbip and other modules make use of both functions while calling the second one could be sufficient to have the list of nodes for a job... Could we merge the 2 in 1 ? ...

**Comment by capitn** [comment]
Be careful, in get_cpuset_values_for_a_moldable_job you can have more hostnames when the oar.conf tag SCHEDULER_RESOURCES_ALWAYS_ASSIGNED_TYPE is used.

Also, maybe get_job_current_hostnames is used in a part of the code where the moldable_job_id is not known.

**Comment by npf** [comment]
well, both are used in oarexec/bipbip using the same Job Id as parameter...

**Comment by capitn** [comment]
I can't see get_cpuset_values_for_a_moldable_job in oarexec and it is always called with "assigned_moldable_job_id" in parameter.

And get_job_current_hostnames is always called with job_id in parameter. Where do you see the problem?

**Comment by npf** [comment]
Ok right. I just got lost.

It needs refactoring.
