### ISSUE TITLE
Importing ssh keys during OAR submission

### ISSUE THREAD

**Issue by camilo1729** [oar-team/oar#40]
I used the following command to import a ssh key for a particular reservation
oarsub -I -l host=2/core=1 -i ~/my_OAR_jobkey

That works without any problem but when I add the suffix .pub I got this:

$ oarsub -I -l host=2/core=1 -i ~/my_OAR_jobkey.pub 
ADMISSION RULE] Set default walltime to 3600.
[ADMISSION RULE] Modify resource description with type constraints
Import job key from file: /home/cruizsanabria/my_OAR_jobkey.pub
Enter passphrase: 

They ask me for a passphrase but I havent set any for my key and at the end it fails:

Error: Fail to extract the public key. Please verify that the job key to import is valid.
OAR_JOB_ID=-14
Oarsub failed: please verify your request syntax or ask for support to your admin.

My question is: 

Is there a way of specifying just my public key?

This behavior leads me to wonder how the private key is being used?.

**Comment by npf** [comment]
what is the purpose of a public key is the private key is unknown ? ;-)
