### ISSUE TITLE
use suexec for oar-api + config auth apache

### ISSUE THREAD

**Issue by npf** [oar-team/oar#44]
suexec ok, but oardocker/jessie does not work

**Comment by bzizou** [comment]
Actually, there are some info about the problems we have with apache 2.4:
http://httpd.apache.org/docs/2.4/fr/env.html#fixheader
...

**Comment by bzizou** [comment]
Fixed in 2.5 branch. 
Should now work fine with apache 2.4.

**Comment by npf** [comment]
On debian apache2-suexec-custom could be used in order to let the api scripts in /usr/lib/cgi-bin.

But using fastcgi+suexec for oarapi conficts with monika: once activated all cgi script are executed with suexec, which breaks monika.

We could rewrite monika to be compatible with suexec/fastcgi (or in php) in order to remove the confict.

However, I think we would better (less work) have to revert to the previous situation: not using suexec/fastcgi for anything, just document how to enable in the installation documentation or oarapi, along with the fact that oarapi must be hosted in a different virtual host or apache server than monika.

**Comment by npf** [comment]
The issue blocks #56

**Comment by npf** [comment]
Closing this issue: 
The proposed solution is to keep suexec/fastcgi, and have monika hosted on a different apache (virtual) hosts than OAR api.
The last update to oar-vagrant provisioning script illustrate that.
