### ISSUE TITLE
oarsh from node to node if not using job_key ?

### ISSUE THREAD

**Issue by npf** [oar-team/oar#49]
I can remember how it is supposed to work when not using job key (-k or --use-job-key or globally OARSUB_FORCE_JOB_KEY in oar.conf)

```
docker@frontend ~
$ oarsub -I -l nodes=2
[ADMISSION RULE] Set default walltime to 7200.
[ADMISSION RULE] Modify resource description with type constraints
OAR_JOB_ID=28
Interactive mode : waiting...
Starting...

Connect to OAR job 28 via the node node2
docker@node2 ~
$ oarsh node3
oarsh: Cannot connect using job id from this host.
```

**Comment by nniclausse** [comment]
any idea ? do we have to use a job key in order to use oarsh inside a job ?

**Comment by npf** [comment]
Nope, OAR has its own job key. User job keys are useful for inter cluster oarsh (grid).
