### ISSUE TITLE
Oarsub fails when used with slash_22=1+nodes=0

### ISSUE THREAD

**Issue by NougatRillettes** [oar-team/oar#54]
Oarsub hangs when invoked as follows : 

```shell
oarsub -t deploy -l slash_22=1+nodes=0,walltime=05:00:00 -I 
```

but works if used like this : 

```shell
oarsub -t deploy -l slash_22=1,walltime=05:00:00 -I 
```

**Comment by npf** [comment]
Hello,

This is a Grid'5000 bug. Please report to Grid'5000 staff.
The Grid'5000 staff would then report here if relevant.

Thx.
