### ISSUE TITLE
oar_resources_add return errors if attribut thread number is not set

### ISSUE THREAD

**Issue by clement-parisot** [oar-team/oar#59]
Hello,

I think there is a problem in the script *oar_resources_add*. When I add a new ressource I got the following error.
```bash
root@oar-server:~# oar_resources_add -H 1 -C 2 -c 8 --host0 124 --auto-offset --host-prefix talc. --host-suffix .nancy.grid5000.fr -A "-p cluster=\"talc\" "
DBD::mysql::st execute failed: Unknown column 'thread' in 'field list' at /usr/share/perl5/OAR/IO.pm line 5071.
DBD::mysql::st fetchrow_array failed: fetch() without execute() at /usr/share/perl5/OAR/IO.pm line 5073.
/!\ Cannot retrive the last value for thread.
oarproperty -c -a host || true
oarproperty -a cpu || true
oarproperty -a core || true
oarproperty -a thread || true
oarnodesetting -a -h 'talc.124.nancy.grid5000.fr' -p host='talc.124.nancy.grid5000.fr' -p cpu=359 -p core=799 -p thread=1 -p cpuset=0 -p cluster="talc"
[...]
```
Errors are due to the fact that I have no column `thread` in my oar database. If I add `thread`as an OAR property there is still an error:
```bash
root@taurus-3:~# oarproperty -a thread
Added property: thread
root@taurus-3:~# oar_resources_add -H 1 -C 2 -c 8 --host0 124 --auto-offset --host-prefix talc. --host-suffix .nancy.grid5000.fr -A "-p cluster=\"talc\""
/!\ Cannot retrive the last value for thread.
oarproperty -c -a host || true
oarproperty -a cpu || true
oarproperty -a core || true
oarproperty -a thread || true
oarnodesetting -a -h 'talc.124.nancy.grid5000.fr' -p host='talc.124.nancy.grid5000.fr' -p cpu=359 -p core=799 -p thread=1 -p cpuset=0 -p cluster="talc"
[...]
```

Finally if I set `thread`property of a random node to 0 value, there is no more warning.

I haven't seen anywhere that `thread`property is mandatory in OAR database. Did I have to add it and set it to a **0** value for all the resources in the database ? Is it an error in the script that *always* set a `thread`property on a new resource ?

Best regards,
Clément
PS: there is also a little typo in "Cannot *retrive*" sentence ;)

**Comment by npf** [comment]
The oar_resources_add tool of oar 2.5.4 proposes a resource hierarchy _with_ threads (see the man page). That was not really a bug.
The new version in 2 5.5 with have thread an option, and nicer warning/error outputs.
Thanks for reporting.
