### ISSUE TITLE
Consecutive oarnodesetting commands results in deadlock in oar Postgres database

### ISSUE THREAD

**Issue by clement-parisot** [oar-team/oar#60]
Hello,
I've got the following problem when executing several `oarnodesetting` commands that modify **State** of a node and another node property called **comment** (char property of a node).

The command:
```bash
oarnodesetting -h "graphene-37.nancy.grid5000.fr" -p "comment=OK"
```
Error on the client side:
```
Update property comment with value OK on node graphene-37.nancy.grid5000.fr ...DBD::Pg::db do failed: ERROR:  deadlock detected
DETAIL:  Process 6950 waits for ShareLock on transaction 188143; blocked by process 6949.
Process 6949 waits for ShareLock on transaction 188144; blocked by process 6950.
HINT:  See server log for query details. at /usr/share/perl5/OAR/IO.pm line 5529.
ERROR (wrong property or wrong value)
```

Error on postgres server:
```SQL
2015-09-25 13:37:03 CEST [unknown] oar@172.16.79.101(49642) ERROR:  deadlock detected
2015-09-25 13:37:03 CEST [unknown] oar@172.16.79.101(49642) DETAIL:  Process 6950 waits for ShareLock on transaction 188143; blocked by process 6949.
	Process 6949 waits for ShareLock on transaction 188144; blocked by process 6950.
	Process 6950: UPDATE resources
	                                    SET comment = 'OK'
	                                    WHERE 
	                                        resources.network_address = 'graphene-37.nancy.grid5000.fr'
	                                   
	Process 6949:   UPDATE resources
	                SET state = 'Alive', finaud_decision = 'NO', state_num = 1
	                WHERE
	                    resource_id = 2293
	             
2015-09-25 13:37:03 CEST [unknown] oar@172.16.79.101(49642) HINT:  See server log for query details.
2015-09-25 13:37:03 CEST [unknown] oar@172.16.79.101(49642) STATEMENT:  UPDATE resources
	                                    SET comment = 'OK'
	                                    WHERE 
	                                        resources.network_address = 'graphene-37.nancy.grid5000.fr'
	                                   
```

**Comment by npf** [comment]
@capitn : est-ce que ca te parle ?

**Comment by capitn** [comment]
Je ne savais pas qu'on pouvait avoir des deadlocks avec les transactions!!!
Je suis passé à côté...
Donc je suppose qu'il y a un des oarnodesetting qui ne fait rien (rollback auto de la transaction)
Il faudrait voir pour faire le begin/commit moins global, peut-être.
Par contre, si ça se passe là, pourquoi on ne l'aurait pas ailleurs dans le code???
Car on n'a rien codé avec ce genre de limitation en tête :-(
À+
Capitn
Le 1 oct. 2015 10:53 AM, Pierre Neyron <notifications@github.com> a écrit :@capitn : est-ce que ca te parle ?

**Comment by lnussbaum** [comment]
A priori, ce scénario peut se produire car:
* oarnodesetting définit nextState, puis notifie Almighty avec ChState
* oarnodesetting continue en définissant une propriété
* en même temps que la définition de la propriété, Almighty change l'état suite à la notification

Du coup, il y a deux transactions qui touchent aux mêmes lignes (sur des colonnes différentes)

**Comment by lnussbaum** [comment]
En fait le problème n'est pas que deux transactions touchent aux mêmes lignes. Ca, c'est géré par postgresql. Le problème est que deux transactions modifient des lignes de la table resources, dans un ordre différent. Donc on est exactement dans le cas décrit au 13.3.4. Deadlocks de http://www.postgresql.org/docs/9.4/static/explicit-locking.html

Il y a deux solutions:
1) (propre) identifier toutes les mises à jour de la table resources, et vérifier qu'à l'intérieur d'une même transaction, elles sont faites dans le même ordre de resource_id. Actuellement, ce n'est le cas ni dans oarnodesetting, ni dans le code d'Almighty qui réagit aux changements d'état, je crois.
2) (sale) réintroduire des locks par table (plutot que par row) avec des commandes LOCK TABLE explicites, au moins pour la table resources.

**Comment by augu5te** [comment]
Effectivement, on l'avait pas vu venir ce coup là et ca pique un peu...

Au regard du cas en exergue (deadlock sur lignes suite à 2 requetes updates avec une clause WHERE resources.network_address)  ca va être pénible d'imposer un ordre "sur les resource_id" . Soit dit en passant cela veut quand même dire que pour 2 clauses where identiques PG mélange les ordres de traitement (à voir si il n'y pas un  moyen pour fixer cet ordre implicite, une option quelque part ???).

Finalement la solution 2 (lock row sur table resource), me semble l'approche la  plus propre. Je releve 17 occurrences dans IO.pm.

**Comment by lnussbaum** [comment]
je pense que si toutes les maj sont factorisées dans un seul UPDATE, plutot que un par network_address ou resource_id, ca devrait passer. Je suppose que le probleme ici est probablement que le oarnodesetting -h "graphene-37.nancy.grid5000.fr" déclenche en fait 4 UPDATE côté Almighty pour les différents resource_id.

**Comment by augu5te** [comment]
Factoriser coté Almighty ca risque d'être plus long, coté oarnodesetting ca semble faisable dans un temps raisonnable... mais la factorisation ne résoud pas le pb de deadlock.
Peux-tu reproduire le pb de deadlock dans oardocker ?

**Comment by lnussbaum** [comment]
en mettant les appels à lock_table autour de la définition des états dans oarnodesetting, oui, je l'avais aussi

**Comment by npf** [comment]
fixed (2.5.6-rc3 deployed on g5k)
