### ISSUE TITLE
oarnodesetting on many nodes is slow

### ISSUE THREAD

**Issue by lnussbaum** [oar-team/oar#61]
Hi,

On Grid'5000, epilogues do:
```ruby
step :oar, :order => 60 do
  # Mark nodes as Absent as they are rebooting
  sh %{/usr/sbin/oarnodesetting -n -s Absent -p available_upto=0 --sql "resource_id IN (select assigned_resources.resource_id from jobs,assigned_resources,resources where assigned_resource_index = 'CURRENT' AND jobs.state = 'Running' AND jobs.job_id = #{job[:id]} and moldable_job_id = jobs.assigned_moldable_job AND (resources.resource_id = assigned_resources.resource_id AND resources.type='default'))"}
end
```
While the SQL subpart is very fast (returns the list of resource_ids in a few ms), the db changes take a very, very long time (minutes) when a few hundred resources. Due to that, the epilogue execution times out, and the nodes end up in an inconsistent state.

Looking at the code, it seems that it does a lot of small UPDATEs (one per resource for the state change, then one per resource for the available_upto change) instead of doing a single request for all resources. Furthermore, each request is done in its own transaction, which means that we pay the price of constraints checking after each request.

Even without switching to a single UPDATE, it should improve the performance to do all the requests in separate transactions (but I have no way to test here).

FTR, this is tracked in https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=6235

**Comment by lnussbaum** [comment]
Looking a bit further:
```perl
           foreach my $r (@resource){
                if (OAR::IO::set_resource_nextState($base,$r,$state) > 0){
                    print("$r --> $state\n");
                    push(@resources_to_check, $r);
                }else{
                    warn("/!\\ The resource $r does not exist in OAR database.\n");
                    $exit_code = 3;
                }
            }
```
This could be optimized by updating all resources at once (UPDATE ... WHERE resource_id IN (<list of @resource))

```perl
# Update properties
if ($#properties >= 0){
    OAR::IO::lock_table($base, ["resources","resource_logs"]);
    if (($#resource >= 0) or (defined($Sql_property))){
        foreach my $r (@resource){
            if (!defined(OAR::IO::get_resource_info($base,$r))){
                warn("/!\\ The resource $r does not exist in OAR database.\n");
                $exit_code = 1;
            }else{
                set_resource_properties($base,$r,\@properties);
            }
        }
```
This could be optimized by introducing a "less-safe" mode that would update all resources at once, without first checking if the resource exists.
The inserts into resource_logs could also be factored by doing mass-inserts using execute_array.

Currently, an update of 480 resources (tested on Reims) generates 2880 SQL queries:
480 updates for the state
480 select to find the resource
480 updates of resource
480 selects to determine the timestamp
480 updates to resource_logs
480 inserts to resource_logs

The above changes could turn it into 6 queries.

**Comment by lnussbaum** [comment]
Also, when Almighty receives the ChState notification, it generates 4330 queries (!). It's not in the critical path for oarnodesetting execution, but still, there's probably a way to do better than that. (See attached log, grep for 20038 ; 20036 is the session from oarnodesetting)
[epilogue-reims.txt](https://github.com/oar-team/oar/files/8239/epilogue-reims.txt)

**Comment by lnussbaum** [comment]
https://github.com/oar-team/oar/pull/62 helps with that by doing the state updates inside a transaction. but it's still a partial fix to the general issue.

**Comment by capitn** [comment]
I think some enhancements can be done in the oarnodesetting command.
I will try to take a look and propose something better (also for #60).

**Comment by npf** [comment]
I think this can be closed.
