### ISSUE TITLE
Automatic oar queues deactivation

### ISSUE THREAD

**Issue by clement-parisot** [oar-team/oar#67]
Hello,
We've got in our OAR configuration several queues that we enable and disable by hand with ``oarnotify`` tool, depending on the platform usage. Here is the list of our queues:

```bash
g5kadmin@oar.nancy.grid5000.fr(xenu|grog):~$ sudo oarnotify -l
testing
	priority = 1
	scheduler = oar_sched_gantt_with_timesharing
	state = notActive
admin
	priority = 10
	scheduler = oar_sched_gantt_with_timesharing
	state = Active
production
	priority = 3
	scheduler = oar_sched_gantt_with_timesharing_and_fairsharing
	state = notActive
g5kschool
	priority = 5
	scheduler = oar_sched_gantt_with_timesharing
	state = notActive
besteffort
	priority = 0
	scheduler = oar_sched_gantt_with_timesharing
	state = Active
challenge
	priority = 3
	scheduler = oar_sched_gantt_with_timesharing_and_fairsharing
	state = Active
default
	priority = 2
	scheduler = oar_sched_gantt_with_timesharing
	state = Active

```

Since few weeks, oar queues have been disabled automaticaly without any action of the admin team. It seems to be oar itself that deactivate queues.

Regarding the log, we find some lines that correspond to this deactivation:
```
[error] [2015-11-17 14:53:36.194] [MetaSched] Error: execution of oar_sched_gantt_with_timesharing_and_fairsharing failed, inactivating queue production (see `oarnotify')
```
I attached the full corresponding logs.
Here are the properties of the faulty job given by Monika:
```
Grid5000 Nancy Production nodes
Job 660090 detailed status:
Job Id	660090
accounted	NO
array_id	660090
array_index	1
assigned_moldable_job	0
checkpoint	0
checkpoint_signal	12
command	./auto_deploy.sh myjessie-x64-nfs.env run_exp/SP_JN10MA.sh
cpuset_name	
exit_code	
file_id	
info_type	fnancy.nancy.grid5000.fr:
initial_request	oarsub -q production -p cluster='talc' -t deploy -l nodes=16,walltime=23:59 -n JN10MA ./auto_deploy.sh myjessie-x64-nfs.env run_exp/SP_JN10MA.sh
job_env	
job_group	
job_name	JN10MA
job_type	PASSIVE
job_user	anugraha
launching_directory	/home/anugraha
message	Job killed by Leon directly
notify	
project	default
properties	((((cluster='talc') AND deploy = 'YES') AND maintenance = 'NO') AND production = 'YES') AND (max_walltime >= 86340 OR max_walltime <= 0)
queue_name	production
reservation	None
resubmit_job_id	0
scheduler_info	
start_time	1970-01-01 01:00:00
state	Error
stderr_file	OAR.JN10MA.%jobid%.stderr
stdout_file	OAR.JN10MA.%jobid%.stdout
stop_time	1970-01-01 01:00:00
submission_time	2015-11-17 13:55:07
suspended	NO
walltime	23:59:0
wanted_resources	-l "{type = 'default'}/host=16,walltime=23:59:0"
```

Automatic deactivation extremely problematic in our context because it blocks all reservations. Moreover, there is no notification process to inform us of this deactivation.

My questions are:
* Considering the logs, do you have an idea of the "error" mentioned by OAR ? Is there a problem with the "fairsharing" scheduler or oarproperties of the job ?
* Is there a notification mechanism in OAR to notify us when this event occurs (queue deactivation) ? Is there a way to disable this feature to let the job scheduling continue ?

Thanks for your time and consideration.
[oar_nancy_queue_deactivation.txt](https://github.com/oar-team/oar/files/37885/oar_nancy_queue_deactivation.txt)

**Comment by capitn** [comment]
Hello,

A queue is deactivated when the scheduler (here "oar_sched_gantt_with_timesharing_and_fairsharing") with a bad exit code or if it was killed.

Usually, in a such case, we have a Perl stack trace with the error but here there is nothing (or the error outputs are redirected elsewhere).
Do you have some related kernel messages (dmesg)? OOM or segfault or ...?

In the log file I just can say that there is a big amount of time between the end of the scheduler and when the meta_sched detects it:

    [debug] [2015-11-17 14:52:23.359] [oar_sched_gantt_with_timesharing_and_fairsharing] End of scheduler for queue production                                                
    [error] [2015-11-17 14:53:36.194] [MetaSched] Error: execution of oar_sched_gantt_with_timesharing_and_fairsharing failed, inactivating queue production (see `oarnotify')

To go further, you can modify the error log message in the file "oar_meta_sched";

    oar_error("[MetaSched] Error: execution of $policy failed, inactivating queue $name (see `oarnotify')\n");

with something like:

    oar_error("[MetaSched] Error: execution of $policy failed, inactivating queue $name (see `oarnotify'). pid=$sched_pid signal=$sched_signal_num dimped_core=$sched_dumped_core\n");

About notification, a mail is sent to `MAIL_RECIPIENT` (in oar.conf) when this error occurs.

**Comment by lnussbaum** [comment]
@capitn: there was an OOM situation on the OAR server at the time. I don't think this is an issue with OAR.

**Comment by npf** [comment]
For 2.5.6 final, I propose to improve a bit the error report however (error code vs signal).
