### ISSUE TITLE
drawgantt with only future view

### ISSUE THREAD

**Issue by lnussbaum** [oar-team/oar#75]
Hi,

As discussed in https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=6415

It would be great if drawgantt was able to only display currently running and future jobs.
Maybe this could be implemented with a "hide finished jobs" checkbox.

**Comment by npf** [comment]
The following could be done:
- add a "start" and "stop" dates option in the "set" menu, beside the "ref time" + "timespan".
- or change the timespan semantic to propose the current "x hours around ref time" but also "x hours after ref time" and maybe "x hours before ref time". 
In both cases, the "perm link" and status line at the bottom must be adapted to reflect that change and still make sens.
