### ISSUE TITLE
oarstat --gantt generates too many queries

### ISSUE THREAD

**Issue by lnussbaum** [oar-team/oar#82]
I've looked at the time taken by:
time oarstat -J --gantt "2014-01-21 00:00:00, 2014-01-22 23:59:59" > /dev/null
(which takes 1min42 on froggy, and 26s on grenoble.grid5000.fr)

The main issue (on froggy) is probably that it generates many small queries. Indeed, the code does:
```
    my %hash_dumper_result;
    my @nodes = OAR::IO::list_resources($base);
    $hash_dumper_result{resources} = \@nodes;
    my %job_gantt = OAR::IO::get_jobs_gantt_scheduled($base,$date_start,$date_stop);
    $hash_dumper_result{jobs} = \%job_gantt;
    #print(Dumper(%hash_dumper_result));
    #print finished or running jobs
    my %jobs_history = OAR::IO::get_jobs_range_dates($base,$date_start,$date_stop);
    foreach my $i (keys(%jobs_history)){
        my $types = OAR::IO::get_job_types_hash($base,$i);
```
Which means that OAR::IO::get_job_types_hash is called for each job in the interval, generating a short SQL query such as:
SELECT type FROM job_types WHERE job_id = 1583778

With the above example, about 25000 queries are generated on grenoble.g5k, taking a total of 10s.
(The remaining 16s of execution are caused on grenoble.g5k by a lack of tuning of the shared_buffers postgresql setting, thus causing lots of filesystem reads)

Generally, it would be a good idea to run postgresql with log_statement = 'all' for some time, and then grep for sessions that have a lot of queries, and identify where they come from (and rewrite the perl code to make less queries).
With:
log_line_prefix = '%t [%p-%l] %q%a %u@%d '

You get entries such as:
```
2016-01-14 23:56:33 CET [29473-25082] [unknown] oarreader@oar2 LOG:  execute <unnamed>:    SELECT type
	                                FROM job_types
	                                WHERE
	                                    job_id = 1589983
```
And 25082 is the number of queries in that session.

**Comment by npf** [comment]
@lnussbaum : do you know where this functionality of oarstat is used ? This is a really old code in OAR, that is mostly used by nobody except G5K. 

 We can remove the sql queries from the loop, but we could also improve what is actually reported by the function... Any wish for that ?

**Comment by npf** [comment]
The following information is given by the drawgantt webapp, but not by oarstat for instance:
  jobs.job_name,
  jobs.project,
  job_types.type

**Comment by npf** [comment]
also network_address are not reported, just resources.

**Comment by lnussbaum** [comment]
I think that the full history is:
1) a long time ago:
-  I needed a way to parse the gantt (to search for specific users)
- I used --gantt for that
- I ran into the -Y perfomance problem, and opened https://intranet.grid5000.fr/bugzilla/show_bug.cgi?id=5403 (oarstat -Y is super slow)
2) recently:
- I ran into the postgresql performance issues on Grid'5000
- bug 5403 was useful to compare with the past performance
- since the performance of oarstat --gantt was still much worse than with mysql, I dug a bit what happened behind the scenes and opened this bug

So, yes, it would be useful to improve it by adding more information, but it's not critical at all for me. I think that it's more important to work on:
> Generally, it would be a good idea to run postgresql with log_statement = 'all' for some time, and then
> grep for sessions that have a lot of queries, and identify where they come from (and rewrite the perl
> code to make less queries).
(oarstat --gantt is just an example here, there was a similar issue when updating properties, and there might be many more out there)
