### ISSUE TITLE
review lock for postgresql in oaraccounting

### ISSUE THREAD

**Issue by npf** [oar-team/oar#83]
@capitn : can you check that the lock for postgresql is OK in oaraccounting in master ?
https://github.com/oar-team/oar/blob/master/sources/core/qfunctions/oaraccounting#L59

**Comment by npf** [comment]
This is the result from the merge of the 2.5 branch (with the fixes for the postgresql locks, but also with mysql still there) and the master branch (where mysql support was removed)

**Comment by npf** [comment]
See diffs with 2.5 and master before merge:

From the master branch:
(master)$ cd sources/core/qfunctions
(master)$ git diff 2.5 oaraccounting
(master)$ git diff before-merge-2.5-20160114  oaraccounting

**Comment by npf** [comment]
@capitn: should we backport this change to 2.5 ?

**Comment by capitn** [comment]
I made some tests and the 2 LOCK statements are OK (in the postgresql doc it is said that the EXCLUSIVE lock blocks the SELECT queries but when I test it is not)

**Comment by npf** [comment]
So we do not change 2.5 ?

**Comment by capitn** [comment]
It is not needed but we can...
