### ISSUE TITLE
Documentation for installation on jessie is not provided

### ISSUE THREAD

**Issue by mickours** [oar-team/oar#86]
Just tell the user that it is in the official debian packages now.

**Comment by npf** [comment]
It missing a bit of context here...

**Comment by mickours** [comment]
Sorry if it is not clear. The Documentation site (http://oar.imag.fr/docs/latest/admin/installation.html)
that explain the installation procedure is not mentionning the debian jessie install (only the  wheezy using a special repository). As it is not required anymore for jessie It would be nice to explain this in the documentation, so the next user that try to install OAR will not loose his time adding a repository he/she do not need.

**Comment by npf** [comment]
For that part, either we replace it by what is in http://oar.imag.fr/download, or we just link to it.

**Comment by npf** [comment]
I think it is fixed with the last online version of the documentation + wiki.

@mickours can you double cjeck and close this issue if correct ? 

thx

**Comment by mickours** [comment]
I can't find installation instructions in the Wiki but the doc is OK now.

**Comment by npf** [comment]
The http://oar.imag.fr/download page links to the documentation and wiki page for oar-vagrant.

The other way around, the documentation links to the download page.

Ok to you ?

**Comment by npf** [comment]
http://oar.imag.fr/docs/2.5/admin/installation.html

Possible improvement: more hyperlinks
-> Download page, Contribs page
-> links in the # lines..

**Comment by mickours** [comment]
I think this is OK now. Closing
